import 'package:hugeicons/hugeicons.dart';

import '../domain/work_log_parts_catalog.dart';

List<List<dynamic>> workLogPartIcon(int partId) =>
    _partIcons[partId] ?? HugeIcons.strokeRoundedTools;

List<List<dynamic>> workLogPartCategoryIcon(WorkLogPartCategory category) =>
    switch (category) {
      WorkLogPartCategory.engine => HugeIcons.strokeRoundedEngine,
      WorkLogPartCategory.vehicle => HugeIcons.strokeRoundedCar05,
      WorkLogPartCategory.tires => HugeIcons.strokeRoundedTire,
      WorkLogPartCategory.chassis => HugeIcons.strokeRoundedSteering,
      WorkLogPartCategory.electronics => HugeIcons.strokeRoundedChip,
      WorkLogPartCategory.brakes => HugeIcons.strokeRoundedDisc,
      WorkLogPartCategory.gearbox => HugeIcons.strokeRoundedTransmission,
    };

const Map<int, List<List<dynamic>>> _partIcons = {
  1: HugeIcons.strokeRoundedEngine,
  2: HugeIcons.strokeRoundedCylinder01,
  3: HugeIcons.strokeRoundedLink02,
  4: HugeIcons.strokeRoundedSettings01,
  5: HugeIcons.strokeRoundedPanelTopBottomDashed,
  6: HugeIcons.strokeRoundedShield01,
  7: HugeIcons.strokeRoundedSparkles,
  8: HugeIcons.strokeRoundedFire02,
  9: HugeIcons.strokeRoundedLink03,
  10: HugeIcons.strokeRoundedLink04,
  11: HugeIcons.strokeRoundedSettings02,
  12: HugeIcons.strokeRoundedOilBarrel,
  13: HugeIcons.strokeRoundedContainer,
  14: HugeIcons.strokeRoundedPipeline,
  15: HugeIcons.strokeRoundedFilter,
  16: HugeIcons.strokeRoundedWindPower,
  17: HugeIcons.strokeRoundedFilterHorizontal,
  18: HugeIcons.strokeRoundedFuel01,
  19: HugeIcons.strokeRoundedFilterVertical,
  20: HugeIcons.strokeRoundedDisc,
  21: HugeIcons.strokeRoundedDisc2,
  22: HugeIcons.strokeRoundedDisc3,
  23: HugeIcons.strokeRoundedDiscAlbum,
  24: HugeIcons.strokeRoundedCircle,
  25: HugeIcons.strokeRoundedCircleSmall,
  26: HugeIcons.strokeRoundedDroplet,
  27: HugeIcons.strokeRoundedWaterPump,
  28: HugeIcons.strokeRoundedArrowDown01,
  29: HugeIcons.strokeRoundedArrowDown02,
  30: HugeIcons.strokeRoundedRefresh01,
  31: HugeIcons.strokeRoundedRefresh03,
  32: HugeIcons.strokeRoundedCircleSlash2,
  33: HugeIcons.strokeRoundedHierarchyCircle01,
  34: HugeIcons.strokeRoundedSteering,
  35: HugeIcons.strokeRoundedWrench01,
  36: HugeIcons.strokeRoundedTransmission,
  37: HugeIcons.strokeRoundedGears,
  38: HugeIcons.strokeRoundedCircleArrowReload01,
  39: HugeIcons.strokeRoundedCirclePile,
  40: HugeIcons.strokeRoundedLink05,
  41: HugeIcons.strokeRoundedSettings03,
  42: HugeIcons.strokeRoundedLink06,
  43: HugeIcons.strokeRoundedArrowLeftRight,
  44: HugeIcons.strokeRoundedCircleArrowReload02,
  45: HugeIcons.strokeRoundedGasPipe,
  46: HugeIcons.strokeRoundedShieldEnergy,
  47: HugeIcons.strokeRoundedHotTube,
  48: HugeIcons.strokeRoundedSlowWinds,
  49: HugeIcons.strokeRoundedRoad01,
  50: HugeIcons.strokeRoundedActivitySpark,
  51: HugeIcons.strokeRoundedElectricityStack,
  52: HugeIcons.strokeRoundedEngineSlash,
  53: HugeIcons.strokeRoundedAutomotiveBattery01,
  54: HugeIcons.strokeRoundedFlash,
  55: HugeIcons.strokeRoundedChip,
  56: HugeIcons.strokeRoundedElectricTower01,
  57: HugeIcons.strokeRoundedElectricPlugs,
  58: HugeIcons.strokeRoundedShield02,
  59: HugeIcons.strokeRoundedLamp01,
  60: HugeIcons.strokeRoundedLamp02,
  61: HugeIcons.strokeRoundedLamp03,
  62: HugeIcons.strokeRoundedLamp04,
  63: HugeIcons.strokeRoundedBulb,
  64: HugeIcons.strokeRoundedBulbCharging,
  65: HugeIcons.strokeRoundedLightbulbOff,
  66: HugeIcons.strokeRoundedLamp05,
  67: HugeIcons.strokeRoundedSpotlight,
  68: HugeIcons.strokeRoundedLamp,
  69: HugeIcons.strokeRoundedArrowLeft01,
  70: HugeIcons.strokeRoundedArrowRight01,
  71: HugeIcons.strokeRoundedArrowLeft02,
  72: HugeIcons.strokeRoundedArrowRight02,
  73: HugeIcons.strokeRoundedTemperature,
  74: HugeIcons.strokeRoundedWaterEnergy,
  75: HugeIcons.strokeRoundedThermometer,
  76: HugeIcons.strokeRoundedCylinder02,
  77: HugeIcons.strokeRoundedFan01,
  78: HugeIcons.strokeRoundedDropletOff,
  79: HugeIcons.strokeRoundedTestTubeDiagonal,
  80: HugeIcons.strokeRoundedCylinder03,
  81: HugeIcons.strokeRoundedPetrolPump,
  82: HugeIcons.strokeRoundedInjection,
  83: HugeIcons.strokeRoundedFuelStation,
  84: HugeIcons.strokeRoundedDashboardCircle,
  85: HugeIcons.strokeRoundedTestTube,
  86: HugeIcons.strokeRoundedTire,
  87: HugeIcons.strokeRoundedFerrisWheel,
  88: HugeIcons.strokeRoundedSafetyPin01,
  89: HugeIcons.strokeRoundedSeatSelector,
  90: HugeIcons.strokeRoundedWindowsNew,
  91: HugeIcons.strokeRoundedWindPower01,
  92: HugeIcons.strokeRoundedWaterfallUp01,
  93: HugeIcons.strokeRoundedMirror,
  94: HugeIcons.strokeRoundedMirroringScreen,
  95: HugeIcons.strokeRoundedMoreHorizontalCircle02,
};
